# Generated by Django 4.2.3 on 2023-08-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0002_alter_advertisement_auction'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE app_advertisments_advertisement RENAME TO advertisement;'),
    ]
